package com.u1.slicer

import com.u1.slicer.data.OverrideMode
import com.u1.slicer.data.OverrideValue
import com.u1.slicer.data.SlicingOverrides
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/** Regression fixtures for the A1 mini PETG V4 cover, offline only. */
class NightPrintV34PreflightTest {
    private fun writeProject(support: Boolean, omitSupportKey: Boolean = false): File {
        val file = File.createTempFile("nightprint-v34", ".3mf")
        val json = """
        {"filament_type":["PETG"],
         "nozzle_temperature":["235"],
         "nozzle_temperature_initial_layer":["235"],
         "textured_plate_temp":["65"],
         "enable_support":"${if (support) "1" else "0"}",
         "layer_height":"0.20",
         "initial_layer_print_height":"0.20",
         "sparse_infill_density":"30%",
         "wall_loops":"5"}
        """.trimIndent().let { project ->
            if (omitSupportKey) project.lineSequence()
                .filterNot { it.contains("\\"enable_support\\"") }
                .joinToString("\\n")
            else project
        }
        ZipOutputStream(file.outputStream()).use { out ->
            out.putNextEntry(ZipEntry("Metadata/project_settings.config"))
            out.write(json.toByteArray())
            out.closeEntry()
        }
        return file
    }

    private fun writeGcode(support: Boolean, outside: Boolean = false): File {
        val file = File.createTempFile("nightprint-v34", ".gcode")
        val badX = if (outside) "-4.93" else "17.5"
        val text = """
            ; generated by OrcaSlicer
            M83
            G90
            ;LAYER_CHANGE
            ;Z:0.2
            G1 Z0.2
            G1 X17.5 Y44.34 E0.3
            G1 X$badX Y45 E0.5
            ;LAYER_CHANGE
            ;Z:0.4
            G1 Z0.4
            G1 X19.5 Y44.34 E0.3
            ; enable_support = ${if (support) "1" else "0"}
        """.trimIndent() + "\n" + "; filler for minimum G-code size\n".repeat(50)
        file.writeText(text)
        return file
    }

    @Test fun supportInSourceAndGcodeAgree() {
        val p = writeProject(true)
        val g = writeGcode(true)
        try {
            assertNull(NightPrintV34Preflight.checkSupport(p, g.path, SlicingOverrides()))
        } finally { p.delete(); g.delete() }
    }

    @Test fun legacy3mfWithoutSupportKeyDefaultsToOff() {
        val p = writeProject(false, omitSupportKey = true)
        val g = writeGcode(false)
        try {
            assertNull(NightPrintV34Preflight.checkSupport(p, g.path, SlicingOverrides()))
        } finally { p.delete(); g.delete() }
    }

    @Test fun rejectsMissingSupportFromActualOutput() {
        val p = writeProject(true)
        val g = writeGcode(false)
        try {
            val issue = NightPrintV34Preflight.checkSupport(p, g.path, SlicingOverrides())
            assertTrue(issue != null && issue.contains("サポート不一致"))
        } finally { p.delete(); g.delete() }
    }

    @Test fun explicitDisableIsComparedToFinalUserOverride() {
        val p = writeProject(true)
        val g = writeGcode(false)
        val overrides = SlicingOverrides(
            supports = OverrideValue(OverrideMode.OVERRIDE, false)
        )
        try {
            assertNull(NightPrintV34Preflight.checkSupport(p, g.path, overrides))
        } finally { p.delete(); g.delete() }
    }

    @Test fun rejectsAnyOutOfBedExtrusionIncludingBrim() {
        val g = writeGcode(true, outside = true)
        try {
            val result = NightPrintGcodeDepositionGuard.audit(g.path)
            assertTrue(result.issue != null && result.issue!!.contains("造形範囲外"))
        } finally { g.delete() }
    }

    @Test fun acceptsActualDepositionInsideA1MiniBed() {
        val g = writeGcode(true, outside = false)
        try {
            val result = NightPrintGcodeDepositionGuard.audit(g.path)
            assertNull(result.issue)
            assertEquals(2, result.metrics!!.layerCount)
        } finally { g.delete() }
    }
}
