package com.u1.slicer

import org.junit.Assert.*
import org.junit.Test
import java.io.File

/** The regression files are tiny fixtures; never send print commands. */
class NightPrintV341GcodeMetadataTest {
    private fun gcode(
        layers: Int = 100,
        material: String = "PETG",
        infill: String = "20%",
        parking: Boolean = true,
    ): File {
        val f = File.createTempFile("nightprint-v341", ".gcode")
        f.bufferedWriter().use { w ->
            w.appendLine("; generated by OrcaSlicer")
            for (n in 1..layers) {
                w.appendLine(";LAYER_CHANGE")
                w.appendLine(";Z:${"%.1f".format(java.util.Locale.US, n * 0.2)}")
                w.appendLine("G1 Z${"%.1f".format(java.util.Locale.US, n * 0.2)}")
                w.appendLine("G1 X90 Y90 E0.22")
                // A Z-hop is NOT a layer change.
                w.appendLine("G0 Z${"%.1f".format(java.util.Locale.US, n * 0.2 + 0.4)}")
            }
            if (parking) w.appendLine("G0 Z148.4 ; end park")
            w.appendLine("; sparse_infill_density = $infill")
            w.appendLine("; filament_type = $material")
            w.appendLine("; nozzle_temperature = 235")
            w.appendLine("; enable_support = 0")
            w.appendLine("; layer_height = 0.2")
        }
        return f
    }

    @Test fun exportedPetgRingUsesActualProcessNotU1Defaults() {
        val f = gcode()
        try {
            val result = NightPrintV341GcodeMetadata.read(f.path)!!
            assertEquals(100, result.printedLayers)
            assertEquals(0.20f, result.infillDensity!!, 0.0001f)
            assertEquals(0.20f, result.layerHeight!!, 0.0001f)
            assertEquals("PETG", result.filamentType)
            assertEquals(235, result.nozzleTemp)
            assertEquals(false, result.supportEnabled)
        } finally { f.delete() }
    }

    @Test fun erroneous129LayerHistoryCorrectedFromHundredMarkers() {
        val f = gcode(100)
        try {
            assertEquals(100, NightPrintV341GcodeMetadata.read(f.path)!!.printedLayers)
        } finally { f.delete() }
    }

    @Test fun missingFooterFieldsDoNotFakeMaterialOrDensity() {
        val f = gcode(layers=2, material="PETG, PLA", infill="unknown")
        try {
            val a = NightPrintV341GcodeMetadata.read(f.path)!!
            assertNull(a.filamentType)
            assertNull(a.infillDensity)
            assertEquals(2, a.printedLayers)
        } finally { f.delete() }
    }

    @Test fun unavailableFileReturnsNull() {
        assertNull(NightPrintV341GcodeMetadata.read("/nonexistent/nightprint-v341.gcode"))
    }
}
