import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { STLLoader } from "three/addons/loaders/STLLoader.js";

const $=id=>document.getElementById(id);
const viewer=$("viewer");
const scene=new THREE.Scene();scene.background=new THREE.Color(0x02070d);
const camera=new THREE.PerspectiveCamera(40,1,0.01,1000000);camera.up.set(0,0,1);camera.position.set(120,-120,95);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;viewer.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.rotateSpeed=.7;controls.zoomSpeed=.9;controls.panSpeed=.8;controls.screenSpacePanning=true;
scene.add(new THREE.HemisphereLight(0xffffff,0x24384e,2.2));const keyLight=new THREE.DirectionalLight(0xffffff,2.8);keyLight.position.set(90,-80,150);scene.add(keyLight);const fillLight=new THREE.DirectionalLight(0x88bfff,1);fillLight.position.set(-100,80,70);scene.add(fillLight);
const grid=new THREE.GridHelper(400,40,0x355575,0x172c40);grid.rotation.x=Math.PI/2;grid.material.opacity=.58;grid.material.transparent=true;scene.add(grid);

const modelGroup=new THREE.Group(),highlightGroup=new THREE.Group(),gizmoGroup=new THREE.Group();
scene.add(modelGroup,highlightGroup,gizmoGroup);
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();

let parts=[],selectionMode="face",selectedPart=-1,selectedPatch=null,selectedOutward=new THREE.Vector3(0,0,1),pointerDown=null,occtPromise=null;
let previewOffset=new THREE.Vector3(),history=[{offset:new THREE.Vector3(),label:"開始"}],historyCursor=0,highlightMesh=null,gizmoBase=new THREE.Vector3();
let selectionLocked=false;
let editSession=null;
let positionCommitted=false;
let selectedEditable=false;

function patchKey(sel=selectedPatch){return sel?sel.partIndex+":"+sel.patchIndex:"";}
function setStatus(t){$("status").textContent=t}
function setLoading(show,text){$("loading").classList.toggle("hidden",!show);if(text)$("loadingText").textContent=text}
function resize(){const r=viewer.getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}
window.addEventListener("resize",resize);new ResizeObserver(resize).observe(viewer);resize();
(function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)})();

function disposeObject(obj){obj.traverse(c=>{c.geometry?.dispose?.();if(Array.isArray(c.material))c.material.forEach(m=>m?.dispose?.());else c.material?.dispose?.()})}
function clearGroup(g){while(g.children.length){const o=g.children[g.children.length-1];g.remove(o);disposeObject(o)}}
function resetHistory(base){previewOffset.copy(base||new THREE.Vector3());history=[{offset:previewOffset.clone(),label:"開始"}];historyCursor=0}
function clearModel(){clearGroup(modelGroup);clearGroup(highlightGroup);clearGroup(gizmoGroup);parts=[];selectedPart=-1;selectedPatch=null;highlightMesh=null;selectedOutward.set(0,0,1);selectionLocked=false;editSession=null;positionCommitted=false;selectedEditable=false;resetHistory(new THREE.Vector3());updateUi()}
function flatArray(v){if(!v)return[];const a=ArrayBuffer.isView(v)?Array.from(v):v;if(Array.isArray(a)&&Array.isArray(a[0]))return a.flat();return Array.isArray(a)?a:Array.from(a)}
function colorFromData(c){if(!Array.isArray(c)||c.length<3)return new THREE.Color(0xaebdca);let[r,g,b]=c.map(Number);if(Math.max(r,g,b)>1.001){r/=255;g/=255;b/=255}return new THREE.Color(Math.max(0,Math.min(1,r)),Math.max(0,Math.min(1,g)),Math.max(0,Math.min(1,b)))}
function createGeometry(md){const pos=flatArray(md?.attributes?.position?.array);if(pos.length<9)return null;const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.Float32BufferAttribute(pos,3));const n=flatArray(md?.attributes?.normal?.array);if(n.length===pos.length)g.setAttribute("normal",new THREE.Float32BufferAttribute(n,3));const idx=flatArray(md?.index?.array);if(idx.length>=3)g.setIndex(idx);if(!g.getAttribute("normal"))g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();return g}
function addPart(geometry,name,source,color,brepFaces){const material=new THREE.MeshStandardMaterial({color:color||0xaebdca,roughness:.7,metalness:.05,side:THREE.DoubleSide});const mesh=new THREE.Mesh(geometry,material);mesh.name=name;mesh.userData.partIndex=parts.length;modelGroup.add(mesh);parts.push({mesh,name,source,brepFaces:Array.isArray(brepFaces)?brepFaces.map(f=>({first:Number(f.first)||0,last:Number(f.last)||0})):[],patches:null,triToPatch:null,patchMode:null})}
function buildStep(result){(result.meshes||[]).forEach((md,i)=>{const g=createGeometry(md);if(g)addPart(g,md.name||("Part "+(i+1)),"step",colorFromData(md.color),md.brep_faces||[])});if(!parts.length)throw new Error("STEP内に表示できる形状がありません。");afterModelLoaded("STEP")}
function buildStl(buffer,name){const g=new STLLoader().parse(buffer);if(!g.getAttribute("normal"))g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();addPart(g,String(name||"STL").replace(/\.stl$/i,""),"stl",new THREE.Color(0x9fb8d8),[]);afterModelLoaded("STL")}
function loadDemo(){clearModel();const box=new THREE.BoxGeometry(52,34,14);box.translate(-34,0,7);addPart(box,"デモ角材","demo",new THREE.Color(0xaebdca),[]);const cyl=new THREE.CylinderGeometry(10,10,32,48,1,false);cyl.rotateX(Math.PI/2);cyl.translate(30,0,16);addPart(cyl,"デモ丸棒","demo",new THREE.Color(0x7899b7),[]);afterModelLoaded("デモ")}
function afterModelLoaded(label){$("fitBtn").disabled=false;fitView();updateUi();setStatus(label+" 読込完了。動かしたい面をタップしてください。")}
async function getOcct(){if(!occtPromise){if(typeof window.occtimportjs!=="function")throw new Error("STEP変換エンジンを読み込めません。");occtPromise=window.occtimportjs({locateFile:path=>"https://cdn.jsdelivr.net/npm/occt-import-js@0.0.23/dist/"+path}).catch(e=>{occtPromise=null;throw e})}return occtPromise}
function looksLikeStepBytes(bytes){if(!bytes?.length)return false;const head=bytes.subarray(0,Math.min(bytes.length,8192));let t="";try{t=new TextDecoder("utf-8",{fatal:false}).decode(head).toUpperCase()}catch(_){for(let i=0;i<head.length;i++)t+=String.fromCharCode(head[i]).toUpperCase()}return t.includes("ISO-10303-21")&&(t.includes("HEADER;")||t.includes("DATA;"))}
function looksLikeStlBytes(bytes){if(!bytes||bytes.length<15)return false;try{const h=new TextDecoder("utf-8",{fatal:false}).decode(bytes.subarray(0,Math.min(bytes.length,4096))).trimStart().toLowerCase();if(h.startsWith("solid")&&h.includes("facet normal"))return true}catch(_){}if(bytes.length>=84){try{const dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),tri=dv.getUint32(80,true);if(tri>0&&84+tri*50===bytes.length)return true}catch(_){}}return false}
async function loadFile(file){if(!file)return;setLoading(true,"3Dデータを確認中…");try{const buffer=await file.arrayBuffer(),bytes=new Uint8Array(buffer),name=String(file.name||""),step=/\.(step|stp)$/i.test(name)||looksLikeStepBytes(bytes),stl=/\.stl$/i.test(name)||looksLikeStlBytes(bytes);if(!step&&!stl)throw new Error("STEP / STLとして認識できません。");clearModel();if(stl&&!step)buildStl(buffer,name);else{const occt=await getOcct(),result=occt.ReadStepFile(bytes,{linearUnit:"millimeter",linearDeflectionType:"bounding_box_ratio",linearDeflection:.003,angularDeflection:.5});if(!result?.success)throw new Error("STEPの解析に失敗しました。");buildStep(result)}}catch(e){console.error(e);clearModel();setStatus("読込失敗: "+(e?.message||String(e)))}finally{setLoading(false)}}

function triangleVertexIndex(g,t,c){return g.index?g.index.getX(t*3+c):t*3+c}
function trianglePoint(g,t,c,target=new THREE.Vector3()){const i=triangleVertexIndex(g,t,c),p=g.getAttribute("position");return target.set(p.getX(i),p.getY(i),p.getZ(i))}
function triangleNormal(g,t,target=new THREE.Vector3()){const a=trianglePoint(g,t,0,new THREE.Vector3()),b=trianglePoint(g,t,1,new THREE.Vector3()),c=trianglePoint(g,t,2,new THREE.Vector3());return target.subVectors(b,a).cross(new THREE.Vector3().subVectors(c,a)).normalize()}
function triangleCountFor(g){return g.index?Math.floor(g.index.count/3):Math.floor(g.getAttribute("position").count/3)}
function positionWeldId(g,vi,cache,map){if(cache.has(vi))return cache.get(vi);const p=g.getAttribute("position"),q=1e5,key=Math.round(p.getX(vi)*q)+","+Math.round(p.getY(vi)*q)+","+Math.round(p.getZ(vi)*q);let id=map.get(key);if(id===undefined){id=map.size;map.set(key,id)}cache.set(vi,id);return id}
function buildPatchesFromBrep(part){const g=part.mesh.geometry,tc=triangleCountFor(g),faces=(part.brepFaces||[]).filter(f=>Number.isFinite(f.first)&&Number.isFinite(f.last)&&f.last>=f.first&&f.first>=0&&f.first<tc);if(faces.length<2||faces.length>250||faces.length>tc*.45)return null;const patches=[],triToPatch=new Int32Array(tc);triToPatch.fill(-1);faces.forEach(f=>{const triangles=[],first=Math.max(0,Math.floor(f.first)),last=Math.min(tc-1,Math.floor(f.last));for(let t=first;t<=last;t++)triangles.push(t);if(!triangles.length)return;const idx=patches.length;triangles.forEach(t=>triToPatch[t]=idx);patches.push({triangles,source:"brep"})});return patches.length?{patches,triToPatch,mode:"STEP面"}:null}
function buildSmoothPatches(part,angleDeg){const g=part.mesh.geometry,tc=triangleCountFor(g),normals=new Array(tc),edgeMap=new Map(),weldMap=new Map(),weldCache=new Map();for(let t=0;t<tc;t++){normals[t]=triangleNormal(g,t,new THREE.Vector3());const ids=[0,1,2].map(c=>positionWeldId(g,triangleVertexIndex(g,t,c),weldCache,weldMap));[[ids[0],ids[1]],[ids[1],ids[2]],[ids[2],ids[0]]].forEach(pair=>{const key=pair[0]<pair[1]?pair[0]+":"+pair[1]:pair[1]+":"+pair[0];let arr=edgeMap.get(key);if(!arr){arr=[];edgeMap.set(key,arr)}arr.push(t)})}const neighbors=Array.from({length:tc},()=>[]);edgeMap.forEach(arr=>{if(arr.length<2)return;for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++){neighbors[arr[i]].push(arr[j]);neighbors[arr[j]].push(arr[i])}});const cosLimit=Math.cos(THREE.MathUtils.degToRad(angleDeg)),triToPatch=new Int32Array(tc);triToPatch.fill(-1);const patches=[];for(let start=0;start<tc;start++){if(triToPatch[start]!==-1)continue;const pi=patches.length,q=[start],triangles=[];triToPatch[start]=pi;while(q.length){const t=q.pop();triangles.push(t);const n=normals[t];neighbors[t].forEach(nb=>{if(triToPatch[nb]!==-1)return;if(n.dot(normals[nb])>=cosLimit){triToPatch[nb]=pi;q.push(nb)}})}patches.push({triangles,source:"smooth"})}return{patches,triToPatch,mode:"自動分割"}}
function ensurePatches(part){if(part.patches)return;let b=part.source==="step"?buildPatchesFromBrep(part):null;if(!b)b=buildSmoothPatches(part,12);part.patches=b.patches;part.triToPatch=b.triToPatch;part.patchMode=b.mode}
function patchStats(part,patch){const g=part.mesh.geometry;part.mesh.updateMatrixWorld(true);const matrix=part.mesh.matrixWorld,normalMatrix=new THREE.Matrix3().getNormalMatrix(matrix),box=new THREE.Box3(),normalSum=new THREE.Vector3();let area=0;const a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3();patch.triangles.forEach(t=>{trianglePoint(g,t,0,a).applyMatrix4(matrix);trianglePoint(g,t,1,b).applyMatrix4(matrix);trianglePoint(g,t,2,c).applyMatrix4(matrix);box.expandByPoint(a);box.expandByPoint(b);box.expandByPoint(c);const cross=new THREE.Vector3().crossVectors(new THREE.Vector3().subVectors(b,a),new THREE.Vector3().subVectors(c,a)),ta=cross.length()*.5;area+=ta;normalSum.addScaledVector(triangleNormal(g,t,new THREE.Vector3()).applyMatrix3(normalMatrix).normalize(),Math.max(ta,.000001))});const size=box.isEmpty()?new THREE.Vector3():box.getSize(new THREE.Vector3()),center=box.isEmpty()?new THREE.Vector3():box.getCenter(new THREE.Vector3());let planar=true;const base=normalSum.lengthSq()>1e-12?normalSum.clone().normalize():new THREE.Vector3(0,0,1);for(const t of patch.triangles){const n=triangleNormal(g,t,new THREE.Vector3()).applyMatrix3(normalMatrix).normalize();if(Math.abs(base.dot(n))<Math.cos(THREE.MathUtils.degToRad(3))){planar=false;break}}const modelCenter=new THREE.Box3().setFromObject(part.mesh).getCenter(new THREE.Vector3());if(base.dot(new THREE.Vector3().subVectors(center,modelCenter))<0)base.multiplyScalar(-1);return{box,size,center,area,type:planar?"平面":"曲面",outward:base}}
function directionName(v){const ax=Math.abs(v.x),ay=Math.abs(v.y),az=Math.abs(v.z);if(az>=ax&&az>=ay)return v.z>=0?"上（Z＋）":"下（Z−）";if(ax>=ay)return v.x>=0?"右（X＋）":"左（X−）";return v.y>=0?"奥（Y＋）":"手前（Y−）"}

function makePatchMesh(part,patch,color,opacity){const pos=[],v=new THREE.Vector3();part.mesh.updateMatrixWorld(true);patch.triangles.forEach(t=>{for(let c=0;c<3;c++){trianglePoint(part.mesh.geometry,t,c,v).applyMatrix4(part.mesh.matrixWorld);pos.push(v.x,v.y,v.z)}});if(!pos.length)return null;const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.Float32BufferAttribute(pos,3));g.computeVertexNormals();const m=new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide,depthTest:false,depthWrite:false});const mesh=new THREE.Mesh(g,m);mesh.renderOrder=90;return mesh}
function highlightPatch(part,patch){clearGroup(highlightGroup);highlightMesh=makePatchMesh(part,patch,0xffc247,.38);if(highlightMesh)highlightGroup.add(highlightMesh)}
function patchVertexIndices(part,patch){const out=new Set();for(const t of patch.triangles)for(let c=0;c<3;c++)out.add(triangleVertexIndex(part.mesh.geometry,t,c));return Array.from(out)}
function expandCoincidentVertexIndices(part,seed,tol=1e-5){const attr=part.mesh.geometry.getAttribute("position"),inv=1/Math.max(tol,1e-9),keys=new Set();for(const i of seed)keys.add(Math.round(attr.getX(i)*inv)+","+Math.round(attr.getY(i)*inv)+","+Math.round(attr.getZ(i)*inv));const out=[];for(let i=0;i<attr.count;i++){const key=Math.round(attr.getX(i)*inv)+","+Math.round(attr.getY(i)*inv)+","+Math.round(attr.getZ(i)*inv);if(keys.has(key))out.push(i)}return out}
function beginEditSession(part,patch){const indices=expandCoincidentVertexIndices(part,patchVertexIndices(part,patch)),attr=part.mesh.geometry.getAttribute("position"),base=new Map();for(const i of indices)base.set(i,[attr.getX(i),attr.getY(i),attr.getZ(i)]);editSession={partIndex:selectedPatch.partIndex,patchIndex:selectedPatch.patchIndex,indices,base};positionCommitted=false}
function worldToLocalDelta(part,worldDelta){part.mesh.updateMatrixWorld(true);const linear=new THREE.Matrix3().setFromMatrix4(part.mesh.matrixWorld).invert();return worldDelta.clone().applyMatrix3(linear)}
function applyGeometryOffset(worldOffset){if(!editSession||!selectedPatch)return;const part=parts[editSession.partIndex];if(!part)return;const attr=part.mesh.geometry.getAttribute("position"),d=worldToLocalDelta(part,worldOffset);for(const i of editSession.indices){const b=editSession.base.get(i);if(!b)continue;attr.setXYZ(i,b[0]+d.x,b[1]+d.y,b[2]+d.z)}attr.needsUpdate=true;part.mesh.geometry.computeVertexNormals();const n=part.mesh.geometry.getAttribute("normal");if(n)n.needsUpdate=true;part.mesh.geometry.computeBoundingBox();part.mesh.geometry.computeBoundingSphere();part.mesh.updateMatrixWorld(true)}
function captureCurrentAsBase(){if(!editSession)return;const part=parts[editSession.partIndex],attr=part.mesh.geometry.getAttribute("position");for(const i of editSession.indices)editSession.base.set(i,[attr.getX(i),attr.getY(i),attr.getZ(i)]);previewOffset.set(0,0,0);resetHistory(new THREE.Vector3());positionCommitted=true}
function revertUncommitted(){if(!editSession)return;if(previewOffset.lengthSq()>1e-12){previewOffset.set(0,0,0);applyGeometryOffset(previewOffset)}editSession=null;positionCommitted=false}
function buildGizmo(center,outward){clearGroup(gizmoGroup);gizmoBase.copy(center);const box=new THREE.Box3().setFromObject(modelGroup),size=box.getSize(new THREE.Vector3()),length=Math.max(size.length()*.1,12),origin=new THREE.Vector3(),dir=outward.clone().normalize();gizmoGroup.add(new THREE.ArrowHelper(dir,origin,length,0xffc247,length*.27,length*.14),new THREE.ArrowHelper(dir.clone().multiplyScalar(-1),origin,length*.58,0x768595,length*.22,length*.12));gizmoGroup.position.set(0,0,0)}

function selectPart(index){if(!parts[index])return;revertUncommitted();selectedPart=index;selectedPatch=null;selectionLocked=false;selectedEditable=false;clearGroup(highlightGroup);clearGroup(gizmoGroup);highlightMesh=null;resetHistory(new THREE.Vector3());updateUi();const size=new THREE.Box3().setFromObject(parts[index].mesh).getSize(new THREE.Vector3());$("selectionTitle").textContent=parts[index].name;$("selectionInfo").textContent="左右幅 "+size.x.toFixed(2)+" / 前後幅 "+size.y.toFixed(2)+" / 高さ "+size.z.toFixed(2)+" mm";setStatus("部品を選びました。面を動かすなら「面を選ぶ」にしてください。")}
function updateSelectedReadout(){if(!selectedPatch)return;const part=parts[selectedPatch.partIndex],patch=part?.patches?.[selectedPatch.patchIndex];if(!part||!patch)return;const stats=patchStats(part,patch),partSize=new THREE.Box3().setFromObject(part.mesh).getSize(new THREE.Vector3());$("selectionTitle").textContent=part.name+" / 面 "+(selectedPatch.patchIndex+1);$("faceType").textContent=stats.type;$("selectionInfo").innerHTML="面：左右 X "+stats.size.x.toFixed(2)+" / 前後 Y "+stats.size.y.toFixed(2)+" / 上下 Z "+stats.size.z.toFixed(2)+" mm"+"<br><strong>部品全体：X "+partSize.x.toFixed(2)+" / Y "+partSize.y.toFixed(2)+" / Z "+partSize.z.toFixed(2)+" mm</strong>"+"<br>面積 "+stats.area.toFixed(2)+" mm² ・ 外方向 "+directionName(selectedOutward);$("faceDimX").textContent=stats.size.x.toFixed(2);$("faceDimY").textContent=stats.size.y.toFixed(2);$("faceDimZ").textContent=stats.size.z.toFixed(2)}
function selectPatchByIndex(index,patchIndex,force=false){if(selectionLocked&&selectedPatch&&!force){setStatus("面選択を固定中です。固定解除してから別の面を選んでください。");return false}revertUncommitted();const part=parts[index];if(!part)return false;ensurePatches(part);const patch=part.patches?.[patchIndex];if(!patch)return false;selectedPart=index;selectedPatch={partIndex:index,patchIndex};resetHistory(new THREE.Vector3());const stats=patchStats(part,patch);selectedOutward.copy(stats.outward);selectedEditable=stats.type==="平面";highlightPatch(part,patch);buildGizmo(stats.center,selectedOutward);beginEditSession(part,patch);updateSelectedReadout();$("directionText").textContent=directionName(selectedOutward);$("easyHelp").innerHTML=selectedEditable?"黄色い面を <strong>外へ出す</strong> / <strong>内へ引っ込める</strong>。本体の側面も一緒に伸び縮みします。":"曲面は形が壊れやすいため、0.4では本体移動を無効にしています。";setStatus(selectedEditable?"本体変形モード。動かすと部品全体の寸法も変わります。":"曲面を選択中。平面を選んでください。");updateUi();return true}
function selectPatchFromHit(hit){const index=hit.object.userData.partIndex,part=parts[index];if(!part)return;ensurePatches(part);const tri=Number(hit.faceIndex);if(!Number.isInteger(tri)||!part.triToPatch||tri<0||tri>=part.triToPatch.length){selectPart(index);return}const pi=part.triToPatch[tri];if(pi<0||!part.patches[pi]){selectPart(index);return}selectPatchByIndex(index,pi)}
function setSelectionMode(mode){selectionMode=mode==="part"?"part":"face";$("partModeBtn").classList.toggle("active",selectionMode==="part");$("faceModeBtn").classList.toggle("active",selectionMode==="face");setStatus(selectionMode==="face"?"面を選ぶ：動かしたい面をタップ":"部品を選ぶ：部品全体をタップ")}
function pickAt(x,y){const r=renderer.domElement.getBoundingClientRect();pointer.x=((x-r.left)/r.width)*2-1;pointer.y=-((y-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(parts.map(p=>p.mesh).filter(m=>m.visible),false)}
renderer.domElement.addEventListener("pointerdown",e=>pointerDown={id:e.pointerId,x:e.clientX,y:e.clientY});
renderer.domElement.addEventListener("pointerup",e=>{if(!pointerDown||pointerDown.id!==e.pointerId)return;const dx=e.clientX-pointerDown.x,dy=e.clientY-pointerDown.y;pointerDown=null;if(Math.hypot(dx,dy)>8)return;const hits=pickAt(e.clientX,e.clientY);if(!hits.length)return;if(selectionMode==="part")selectPart(hits[0].object.userData.partIndex);else selectPatchFromHit(hits[0])});

function pushSnapshot(label){history=history.slice(0,historyCursor+1);history.push({offset:previewOffset.clone(),label});historyCursor=history.length-1;positionCommitted=false;updateUi()}
function moveByVector(vector,amount,label){if(!selectedPatch||!selectedEditable||!Number.isFinite(amount)||amount===0)return;previewOffset.addScaledVector(vector,amount);pushSnapshot(label+" "+Math.abs(amount).toFixed(2)+" mm");applyPreviewTransform()}
function moveNormal(amount){moveByVector(selectedOutward.clone().normalize(),amount,amount>0?"外へ":"内へ")}
function moveAxis(axis,sign){const amount=Math.abs(Number($("moveAmount").value));if(!Number.isFinite(amount)||amount<=0)return;const v=new THREE.Vector3();v[axis]=sign;const names={"x-":"左へ","x+":"右へ","y-":"手前へ","y+":"奥へ","z+":"上へ","z-":"下へ"};moveByVector(v,amount,names[axis+(sign>0?"+":"-")])}
function applyPreviewTransform(){if(!selectedPatch||!editSession)return;applyGeometryOffset(previewOffset);const part=parts[selectedPatch.partIndex],patch=part?.patches?.[selectedPatch.patchIndex];if(part&&patch)highlightPatch(part,patch);gizmoGroup.position.copy(previewOffset);$("previewValue").textContent="左右 "+previewOffset.x.toFixed(2)+" / 前後 "+previewOffset.y.toFixed(2)+" / 上下 "+previewOffset.z.toFixed(2)+" mm";updateSelectedReadout();updateUi()}
function resetPreview(){if(!selectedPatch||!editSession)return;previewOffset.set(0,0,0);history=[{offset:new THREE.Vector3(),label:"開始"}];historyCursor=0;positionCommitted=false;applyPreviewTransform()}
function undo(){if(historyCursor<=0)return;historyCursor--;previewOffset.copy(history[historyCursor].offset);applyPreviewTransform()}
function redo(){if(historyCursor>=history.length-1)return;historyCursor++;previewOffset.copy(history[historyCursor].offset);applyPreviewTransform()}
function toggleSelectionLock(){if(!selectedPatch)return;selectionLocked=!selectionLocked;updateUi();setStatus(selectionLocked?"面選択を固定しました。別の面を触っても変わりません。":"面選択固定を解除しました。")}
function togglePositionFix(){if(!selectedPatch||!selectedEditable||!editSession)return;captureCurrentAsBase();const part=parts[selectedPatch.partIndex],patch=part?.patches?.[selectedPatch.patchIndex];if(part&&patch){const stats=patchStats(part,patch);gizmoBase.copy(stats.center);gizmoGroup.position.set(0,0,0);highlightPatch(part,patch)}updateSelectedReadout();updateUi();setStatus("この位置を本体形状に固定しました。別の面を選んでも形は保持されます。")}

function renderHistory(){const list=$("historyList"),visible=history.slice(1,historyCursor+1);$("historyCount").textContent=String(visible.length);if(!visible.length){list.innerHTML='<div class="empty">まだ操作していません</div>';return}list.innerHTML="";visible.forEach((item,i)=>{const row=document.createElement("div");row.className="historyItem";const strong=document.createElement("strong");strong.textContent=item.label;const small=document.createElement("small");small.textContent="#"+(i+1);row.append(strong,small);list.appendChild(row)})}
function updateUi(){const has=!!selectedPatch,canEdit=has&&selectedEditable;$("partCount").textContent=String(parts.length);$("selectedKind").textContent=has?"面":(selectedPart>=0?"部品":"—");$("selectedFace").textContent=has?String(selectedPatch.patchIndex+1):"—";$("directionBadge").classList.toggle("hidden",!has);$("faceDimsHud").classList.toggle("hidden",!has);document.querySelectorAll("[data-normal-delta]").forEach(b=>b.disabled=!canEdit);document.querySelectorAll("[data-dir-axis]").forEach(b=>b.disabled=!canEdit);$("customOutBtn").disabled=!canEdit;$("customInBtn").disabled=!canEdit;$("resetPreviewBtn").disabled=!canEdit||previewOffset.lengthSq()<1e-12;$("undoBtn").disabled=historyCursor<=0;$("redoBtn").disabled=historyCursor>=history.length-1;$("selectionLockBtn").disabled=!has;$("positionFixBtn").disabled=!canEdit;$("selectionLockBtn").classList.toggle("active",selectionLocked);$("selectionLockBtn").textContent=selectionLocked?"🔒 面選択 固定中":"🔓 面選択を固定";$("positionFixBtn").classList.toggle("active",positionCommitted);$("positionFixBtn").textContent=positionCommitted?"✓ 本体に固定済み":"✓ この位置を固定";$("lockInfo").textContent="面選択固定："+(selectionLocked?"ON":"OFF")+"　／　本体位置："+(positionCommitted?"固定済み":"編集中");if(!has){$("faceType").textContent="—";$("directionText").textContent="—";$("easyHelp").textContent="まず3Dモデルの面をタップしてください。"}renderHistory()}
function fitView(){if(!parts.length)return;const box=new THREE.Box3().setFromObject(modelGroup);if(box.isEmpty())return;const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),span=Math.max(size.x,size.y,size.z,1);controls.target.copy(center);camera.position.set(center.x+span*1.35,center.y-span*1.35,center.z+span*1.05);camera.near=Math.max(span/5000,.01);camera.far=Math.max(span*200,1000);camera.updateProjectionMatrix();controls.update()}

$("fileInput").addEventListener("click",function(){this.value=""});$("fileInput").addEventListener("change",function(){loadFile(this.files?.[0])});$("demoBtn").addEventListener("click",loadDemo);$("fitBtn").addEventListener("click",fitView);$("partModeBtn").addEventListener("click",()=>setSelectionMode("part"));$("faceModeBtn").addEventListener("click",()=>setSelectionMode("face"));
document.querySelectorAll("[data-normal-delta]").forEach(b=>b.addEventListener("click",()=>moveNormal(Number(b.dataset.normalDelta))));
$("customOutBtn").addEventListener("click",()=>{const n=Math.abs(Number($("moveAmount").value));if(n>0)moveNormal(n)});$("customInBtn").addEventListener("click",()=>{const n=Math.abs(Number($("moveAmount").value));if(n>0)moveNormal(-n)});
document.querySelectorAll("[data-dir-axis]").forEach(b=>b.addEventListener("click",()=>moveAxis(b.dataset.dirAxis,Number(b.dataset.dirSign))));
$("resetPreviewBtn").addEventListener("click",resetPreview);$("undoBtn").addEventListener("click",undo);$("redoBtn").addEventListener("click",redo);$("selectionLockBtn").addEventListener("click",toggleSelectionLock);$("positionFixBtn").addEventListener("click",togglePositionFix);

setSelectionMode("face");updateUi();window.__OKACAD_NEXT_READY__=true;
window.__OKACAD_NEXT_TEST__={
  loadDemo,
  selectFace:(p,f,force=false)=>selectPatchByIndex(p,f,force),
  moveNormal,
  toggleSelectionLock,
  togglePositionFix,
  getPreview:()=>({x:previewOffset.x,y:previewOffset.y,z:previewOffset.z}),
  getSelected:()=>selectedPatch?{...selectedPatch}:null,
  isSelectionLocked:()=>selectionLocked,
  isFixed:()=>positionCommitted,
  isEditable:()=>selectedEditable,
  getPartSize:(p=0)=>{const part=parts[p];if(!part)return null;const s=new THREE.Box3().setFromObject(part.mesh).getSize(new THREE.Vector3());return{x:s.x,y:s.y,z:s.z}}
};
